#!/usr/bin/env bash
# ============================================================
#  Multi-Format Password Cracker — One-Line Installer
#  Repo: https://github.com/NRXQuantum/telegram-bot-zip
#
#  Token source priority:
#    1. config.py  ← RECOMMENDED (edit this file)
#    2. TELEGRAM_BOT_TOKEN env var
#    3. .env file  (legacy)
# ============================================================
set -euo pipefail

REPO_RAW="${REPO_RAW:-https://raw.githubusercontent.com/NRXQuantum/telegram-bot-zip/main}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/.zip_cracker}"
PY_SCRIPT="zip_cracker.py"
CONFIG_FILE="config.py"
MAX_TOKEN_ATTEMPTS=3

if [ -t 1 ]; then
    CYN=$'\033[0;36m'; GRN=$'\033[0;32m'; YEL=$'\033[1;33m'
    RED=$'\033[0;31m'; BLD=$'\033[1m'; NC=$'\033[0m'
else
    CYN=""; GRN=""; YEL=""; RED=""; BLD=""; NC=""
fi
log()  { printf '%s[*]%s %s\n' "$CYN" "$NC" "$*"; }
ok()   { printf '%s[+]%s %s\n' "$GRN" "$NC" "$*"; }
warn() { printf '%s[!]%s %s\n' "$YEL" "$NC" "$*"; }
die()  { printf '%s[✗]%s %s\n' "$RED" "$NC" "$*" >&2; exit 1; }

banner() {
cat <<'EOF'
   ______               ____                _
  |__  (_)_ __       / ___|_ __ __ _  ___| | _____ _ __
    / /| | '_ \     | |   | '__/ _ |/ __| |/ / _ \ '__|
   / /_| | |_) |    | |___| | | (_| | (__|   <  __/ |
  /____|_| .__/      \____|_|  \__,_|\___|_|\_\___|_|
         |_|        telegram-bot-zip
EOF
echo
}

ask() {
    local prompt="$1" varname="$2" default="${3:-}" ans=""
    if [ -t 0 ]; then
        read -rp "$prompt" ans || true
    elif [ -c /dev/tty ] && [ -r /dev/tty ]; then
        read -rp "$prompt" ans < /dev/tty || true
    else
        ans="$default"
    fi
    eval "$varname=\$ans"
}

run_as_root() {
    if [ "$(id -u)" -eq 0 ]; then "$@"
    elif command -v sudo >/dev/null 2>&1; then sudo "$@"
    else "$@"; fi
}

# ---------- Read token from config.py ----------
read_token_from_config() {
    local cfg="$1"
    [ -f "$cfg" ] || return 1
    grep -E '^[[:space:]]*TELEGRAM_BOT_TOKEN[[:space:]]*=' "$cfg" 2>/dev/null \
        | head -n1 \
        | sed -E 's/^[^=]*=[[:space:]]*//' \
        | sed -E 's/^"(.*)".*$/\1/' \
        | sed -E "s/^'(.*)'.*\$/\1/" \
        | sed -E 's/#.*$//' \
        | xargs 2>/dev/null || true
}

# ---------- Write token to config.py ----------
write_config() {
    local cfg="$1"
    local token="$2"
    umask 077
    cat > "$cfg" <<EOF
"""
Telegram Bot Configuration
Auto-generated by install.sh
"""

TELEGRAM_BOT_TOKEN = "$token"

# Optional settings
DEFAULT_PORT = 5000
MAX_WORKERS = 128
MAX_CRC_FILE_SIZE = 3
MASK_CHUNK_SIZE = 100000
CLEANUP_INTERVAL = 3600
IDLE_TIMEOUT = 3600
JOB_TTL = 3600
EOF
    chmod 600 "$cfg" 2>/dev/null || true
}

# ---------- Telegram token validation ----------
validate_token() {
    local token="$1"
    [ -z "$token" ] && return 1
    local resp=""
    if command -v curl >/dev/null 2>&1; then
        resp=$(curl -fsSL --max-time 10 \
            "https://api.telegram.org/bot${token}/getMe" 2>/dev/null || echo "")
    elif command -v wget >/dev/null 2>&1; then
        resp=$(wget -q -O - --timeout=10 \
            "https://api.telegram.org/bot${token}/getMe" 2>/dev/null || echo "")
    else
        return 0
    fi
    echo "$resp" | grep -q '"ok":true'
}

extract_username() {
    local token="$1" resp=""
    if command -v curl >/dev/null 2>&1; then
        resp=$(curl -fsSL --max-time 10 \
            "https://api.telegram.org/bot${token}/getMe" 2>/dev/null || echo "")
    fi
    echo "$resp" | sed -n 's/.*"username":"\([^"]*\)".*/\1/p'
}

# ---------- Token gate (blocks launch if invalid) ----------
token_gate() {
    local cfg_file="$INSTALL_DIR/$CONFIG_FILE"
    local attempt=0
    local current_token=""

    while [ "$attempt" -lt "$MAX_TOKEN_ATTEMPTS" ]; do
        attempt=$((attempt + 1))

        # Read token (priority: config.py → env var → .env)
        current_token=$(read_token_from_config "$cfg_file" || true)

        if [ -z "$current_token" ] || [ "$current_token" = "PASTE_YOUR_TOKEN_HERE" ]; then
            current_token="${TELEGRAM_BOT_TOKEN:-}"
        fi

        if [ -z "$current_token" ] && [ -f "$INSTALL_DIR/.env" ]; then
            current_token=$(grep -E '^[[:space:]]*TELEGRAM_BOT_TOKEN[[:space:]]*=' \
                "$INSTALL_DIR/.env" 2>/dev/null \
                | head -n1 \
                | sed -E 's/^[^=]*=[[:space:]]*//' \
                | tr -d '\r\n' \
                | xargs 2>/dev/null || true)
        fi

        if [ -n "$current_token" ] && [ "$current_token" != "PASTE_YOUR_TOKEN_HERE" ]; then
            log "Validating token (attempt $attempt/$MAX_TOKEN_ATTEMPTS)..."
            if validate_token "$current_token"; then
                local uname
                uname=$(extract_username "$current_token")
                echo
                ok "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                ok "  ✅ TOKEN IS VALID"
                ok "     Bot: @${uname}"
                ok "     Source: config.py"
                ok "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                echo
                return 0
            else
                echo
                warn "❌ Token invalid (attempt $attempt/$MAX_TOKEN_ATTEMPTS)"
                warn "   Preview: ${current_token:0:12}...${current_token: -4}"
                echo
            fi
        else
            warn "No token found in config.py, env, or .env"
            echo
        fi

        if [ -t 1 ] && { [ -t 0 ] || [ -c /dev/tty ]; }; then
            echo "${BLD}BotFather → @BotFather → /newbot → টোকেন কপি${NC}"
            echo
            ask "Paste NEW TELEGRAM_BOT_TOKEN (Ctrl+C to abort): " NEW_TOKEN ""
            if [ -z "${NEW_TOKEN:-}" ]; then continue; fi
            write_config "$cfg_file" "$NEW_TOKEN"
            ok "Token saved to config.py — validating next attempt..."
            echo
        else
            die "Token invalid and no TTY. Edit $cfg_file manually."
        fi
    done

    die "Token validation failed after $MAX_TOKEN_ATTEMPTS attempts."
}

# ---------- Kill previous bot ----------
kill_previous_bot() {
    if command -v pgrep >/dev/null 2>&1; then
        local PIDS
        PIDS=$(pgrep -f "$PY_SCRIPT" 2>/dev/null || true)
        if [ -n "$PIDS" ]; then
            warn "Old instance(s): $PIDS — killing..."
            kill $PIDS 2>/dev/null || true
            sleep 2
            local STILL
            STILL=$(pgrep -f "$PY_SCRIPT" 2>/dev/null || true)
            [ -n "$STILL" ] && kill -9 $STILL 2>/dev/null || true
            ok "Previous instance cleared."
        fi
    fi
}

# ---------- Environment detection ----------
detect_env() {
    if [ -n "${TERMUX_VERSION:-}" ] || [ -d "/data/data/com.termux" ]; then
        ENV_TYPE="termux"
    elif [ "$(uname -s 2>/dev/null)" = "Darwin" ]; then
        ENV_TYPE="macos"
    elif command -v apt-get >/dev/null 2>&1; then
        ENV_TYPE="debian"
    elif command -v pacman >/dev/null 2>&1; then
        ENV_TYPE="arch"
    elif command -v dnf >/dev/null 2>&1; then
        ENV_TYPE="fedora"
    else
        ENV_TYPE="unknown"
    fi
    ok "Environment: $ENV_TYPE"
    [ -d "/content" ] && [ "$(id -u)" -eq 0 ] && \
        warn "Detected Google Colab / Docker root environment."
}

ensure_python() {
    if ! command -v python3 >/dev/null 2>&1; then
        log "Installing python3..."
        case "$ENV_TYPE" in
            termux)  pkg install -y python ;;
            debian)  run_as_root apt-get install -y python3 ;;
            arch)    run_as_root pacman -Sy --noconfirm python ;;
            fedora)  run_as_root dnf install -y python3 ;;
            macos)   brew install python ;;
            *)       die "python3 missing" ;;
        esac
    fi
    ok "Python: $(python3 --version 2>&1)"

    if ! python3 -m pip --version >/dev/null 2>&1; then
        case "$ENV_TYPE" in
            termux)  pkg install -y python-pip ;;
            debian)  run_as_root apt-get install -y python3-pip ;;
            arch)    run_as_root pacman -Sy --noconfirm python-pip ;;
            fedora)  run_as_root dnf install -y python3-pip ;;
            macos)   python3 -m ensurepip --upgrade || brew install python ;;
        esac
    fi
}

install_system_deps() {
    log "Installing system dependencies..."
    case "$ENV_TYPE" in
        termux)
            pkg update -y >/dev/null 2>&1 || true
            pkg install -y python unrar p7zip clang make libffi openssl \
                python-psutil >/dev/null 2>&1 || warn "Some termux packages failed"
            ;;
        debian)
            run_as_root apt-get update -qq >/dev/null 2>&1 || true
            run_as_root apt-get install -y \
                python3 python3-venv python3-pip \
                unrar-free p7zip-full build-essential \
                libffi-dev libssl-dev python3-dev \
                >/dev/null 2>&1 || warn "Some apt packages failed"
            ;;
        arch)
            run_as_root pacman -Sy --noconfirm \
                python python-pip unrar p7zip base-devel \
                >/dev/null 2>&1 || warn "Some pacman packages failed"
            ;;
        fedora)
            run_as_root dnf install -y \
                python3 python3-pip python3-devel \
                unrar p7zip p7zip-plugins gcc \
                libffi-devel openssl-devel \
                >/dev/null 2>&1 || warn "Some dnf packages failed"
            ;;
        macos)
            brew install python unrar p7zip >/dev/null 2>&1 || true
            ;;
        *)
            warn "Unknown OS — skipping system packages."
            ;;
    esac
    ok "System deps done."
}

install_python_deps() {
    log "Setting up Python environment..."
    cd "$INSTALL_DIR"

    if ! python3 -m venv --help >/dev/null 2>&1; then
        warn "python3-venv missing — installing..."
        case "$ENV_TYPE" in
            termux)  pkg install -y python ;;
            debian)  run_as_root apt-get install -y python3-venv || true ;;
            arch)    run_as_root pacman -Sy --noconfirm python || true ;;
            fedora)  run_as_root dnf install -y python3 || true ;;
            macos)   brew install python || true ;;
        esac
    fi

    [ -d ".venv" ] && [ ! -f ".venv/bin/activate" ] && {
        warn "Broken .venv — removing."
        rm -rf .venv
    }

    VENV_OK=0
    if [ -f ".venv/bin/activate" ]; then
        VENV_OK=1
        ok "Existing virtualenv valid."
    else
        log "Creating virtualenv..."
        if python3 -m venv .venv 2>/dev/null && [ -f ".venv/bin/activate" ]; then
            VENV_OK=1
            ok "Virtualenv created."
        else
            warn "venv failed — using system pip fallback."
            rm -rf .venv
        fi
    fi

    local PIP_EXTRA=""
    if [ "$VENV_OK" = "1" ]; then
        # shellcheck disable=SC1091
        source .venv/bin/activate
        PIP="pip"
    elif [ "$(id -u)" -eq 0 ]; then
        PIP="pip3"; PIP_EXTRA="--break-system-packages"
        warn "Root — using --break-system-packages"
    else
        PIP="pip3"; PIP_EXTRA="--user"
        warn "Using user pip"
    fi

    log "Installing Python packages..."
    $PIP install $PIP_EXTRA --upgrade pip wheel >/dev/null 2>&1 || true

    [ "$ENV_TYPE" = "termux" ] && pkg install -y python-psutil >/dev/null 2>&1 || true

    $PIP install $PIP_EXTRA \
        pyzipper rarfile py7zr PyPDF2 flask python-telegram-bot \
        2>&1 | tail -3 || {
        warn "Bulk failed — retrying individually..."
        for pkg in pyzipper rarfile py7zr PyPDF2 flask python-telegram-bot; do
            $PIP install $PIP_EXTRA "$pkg" >/dev/null 2>&1 || \
                warn "  → Failed: $pkg"
        done
    }

    log "Verifying..."
    local CHECK_PY
    [ "$VENV_OK" = "1" ] && CHECK_PY=".venv/bin/python" || CHECK_PY="python3"
    local MISSING=""
    for mod in pyzipper rarfile py7zr PyPDF2 flask telegram; do
        $CHECK_PY -c "import $mod" 2>/dev/null || MISSING="$MISSING $mod"
    done
    [ -n "$MISSING" ] && warn "Missing modules:$MISSING" || ok "All modules verified."
    ok "Python deps done."
}

fetch_script() {
    cd "$INSTALL_DIR"

    # zip_cracker.py
    if [ ! -f "$PY_SCRIPT" ]; then
        log "Downloading $PY_SCRIPT..."
        if command -v curl >/dev/null 2>&1; then
            curl -fsSL "$REPO_RAW/$PY_SCRIPT" -o "$PY_SCRIPT"
        elif command -v wget >/dev/null 2>&1; then
            wget -q "$REPO_RAW/$PY_SCRIPT" -O "$PY_SCRIPT"
        else
            die "Neither curl nor wget found."
        fi
        [ -s "$PY_SCRIPT" ] || die "Download failed."
        ok "$PY_SCRIPT downloaded."
    else
        ok "$PY_SCRIPT already present."
    fi

    # config.py (create from template only if missing)
    if [ ! -f "$CONFIG_FILE" ]; then
        log "Creating $CONFIG_FILE template..."
        write_config "$INSTALL_DIR/$CONFIG_FILE" "PASTE_YOUR_TOKEN_HERE"
        ok "$CONFIG_FILE created."
    else
        ok "$CONFIG_FILE already present."
    fi

    # password_list.txt
    if [ ! -f "password_list.txt" ]; then
        if command -v curl >/dev/null 2>&1; then
            curl -fsSL "$REPO_RAW/password_list.txt" -o password_list.txt 2>/dev/null || true
        fi
    fi
}

setup_token_from_env() {
    # If TELEGRAM_BOT_TOKEN env var is set, write it to config.py
    if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
        ok "TELEGRAM_BOT_TOKEN env var detected — writing to config.py"
        write_config "$INSTALL_DIR/$CONFIG_FILE" "$TELEGRAM_BOT_TOKEN"
    fi
}

create_launcher() {
    local LAUNCHER="$INSTALL_DIR/run.sh"
    cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
cd "\$(dirname "\$0")"

SCRIPT_NAME="$PY_SCRIPT"

if command -v pgrep >/dev/null 2>&1; then
    PIDS=\$(pgrep -f "\$SCRIPT_NAME" 2>/dev/null || true)
    if [ -n "\$PIDS" ]; then
        echo "[!] Killing old: \$PIDS"
        kill \$PIDS 2>/dev/null || true
        sleep 2
        STILL=\$(pgrep -f "\$SCRIPT_NAME" 2>/dev/null || true)
        [ -n "\$STILL" ] && kill -9 \$STILL 2>/dev/null || true
    fi
fi

if [ -f ".venv/bin/activate" ]; then
    # shellcheck disable=SC1091
    source .venv/bin/activate
    exec python "\$SCRIPT_NAME" "\$@"
else
    exec python3 "\$SCRIPT_NAME" "\$@"
fi
EOF
    chmod +x "$LAUNCHER"
    ok "Launcher created: $LAUNCHER"
}

main() {
    banner
    detect_env
    ensure_python
    install_system_deps

    mkdir -p "$INSTALL_DIR"
    cd "$INSTALL_DIR"

    kill_previous_bot
    fetch_script
    install_python_deps
    setup_token_from_env
    create_launcher

    echo
    log "═══════════════════════════════════════════════════════"
    log "  Pre-launch token validation"
    log "═══════════════════════════════════════════════════════"
    token_gate

    echo
    ok "Installation complete!"
    echo
    echo "  ${CYN}~/.zip_cracker/run.sh --bot${NC}                # bot only"
    echo "  ${CYN}~/.zip_cracker/run.sh --web --port 5000${NC}    # web only"
    echo "  ${CYN}~/.zip_cracker/run.sh --all${NC}                # bot + web"
    echo "  ${CYN}nano ~/.zip_cracker/config.py${NC}              # edit token"
    echo

    if command -v pgrep >/dev/null 2>&1 && pgrep -f "$PY_SCRIPT" >/dev/null 2>&1; then
        warn "Waiting 10s for Telegram to release old session..."
        sleep 10
    fi

    echo
    ok "Starting bot (Ctrl+C to stop)..."
    echo
    exec "$INSTALL_DIR/run.sh" --bot
}

main "$@"
